# Generated by Django 5.2.6 on 2025-09-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
