# Generated by Django 5.2.6 on 2025-09-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='max_detailed',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='max_images',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='max_results',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
