# Generated by Django 5.2.6 on 2025-09-19 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='configuration',
            field=models.ForeignKey(blank=True, help_text='Configuração de IA para scraping deste site', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='configurations.configuration'),
        ),
    ]
