# Generated by Django 5.2.6 on 2025-10-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='oracle_password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
